### PR TITLE
feat: allow to attach external SG to the documentDB

### PR DESCRIPTION
**Pull request by rasta-rocket**
## what

Hey folks 👋 

First of all thanks for the work 💪 

Here the goal is to allow the user of the module to attach security groups which are managed outside of the module

## why

This is pretty useful, when you have some design where security groups are centrally managed and so outside of the scope of the module

## references

Note: If you have any questions don't hesitate to ping me 😉 

Cheers ☀️

### CODE REVIEW

**Comment by kevcube** [comment]
@rasta-rocket it helps to make a post about PRs in #pr-reviews channel of Cloudposse's slack

**Comment by rasta-rocket** [comment]
@kevcube sorry for the late answer any possibility for you to review this ?

**Review by kevcube — APPROVED** [review]

**Comment by rasta-rocket** [comment]
@kevcube Thank you  !!! 🤩 

Do you know how the releasing is performed on that module ?

**Comment by kevcube** [comment]
@rasta-rocket actually I do not.. I thought it would release automatically but I'm not sure why it didn't. I'll investigate, but you should be able to reference via commit hash for now

**Pull request merged**
