### PR TITLE
Enable intra-security group traffic on DB port

### PR DESCRIPTION
**Pull request by kevcube**
## what

* adds variable `allow_ingress_from_self` which configures the security group to allow traffic within itself on DB port

## why

* This is useful in architectures where the db security group will be used to control db access - i.e. it will also be applied to applications.

## references

https://github.com/cloudposse/terraform-aws-rds-cluster/pull/145

### CODE REVIEW

**Comment by Benbentwo** [comment]
can you update the readme with

```shell
make init
make readme
```

Looking into why it doesn't happen automatically

**Comment by max-lobur** [comment]
Try `make precommit/terraform` - it should fix both format and the readme

**Comment by kevcube** [comment]
@Benbentwo @max-lobur done

**Review by max-lobur — APPROVED** [review]

**Pull request merged**
