### PR TITLE
add variable certificate change

### PR DESCRIPTION
**Pull request by rabihaggle**
## what

We need to have the possibility to select the certificate we need to use, or directly the default amazon one.

## why

Because https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL-certificate-rotation.html

## references

Please read the link -> https://docs.aws.amazon.com/es_es/documentdb/latest/developerguide/ca_cert_rotation.html

### CODE REVIEW

**Comment by Gowiem** [comment]
@rabihaggle Please run the following commands, commit, and push the changes:

```
make init
make github/init
make readme
```

**Comment by Gowiem** [comment]
@rabihaggle did you add all the changes from `make readme`? The tests are still failing in regards to README differences, so if you can please try running that again and adding all changes. If there are no changes post-command, then please screenshot your terminal to verify that and I'll share internally with the rest of the contributors to point that out as a bug we need to fix ASAP (since that'll block all contributions). 

Thanks!

**Comment by rabihaggle** [comment]
I have already corrected the problem, brew install gomplate, https://archive.sweetops.com/build-harness/2020/01/.

but I'm seeing that lines have been deleted that shouldn't have been.

**Review by Gowiem — APPROVED** [review]
LGTM

**Review by Gowiem — APPROVED** [review]
LGTM

**Review by nitrocode — APPROVED** [review]

**Comment by max-lobur** [comment]
```
brew install make
make --version
GNU Make 4.4.1

make precommit/terraform # Run dockerized version of precommit hook that we use in CI.
```

**Review by max-lobur — APPROVED** [review]

**Pull request merged**
