### PR TITLE
test: update test framework to use latest best practices and reduce boilerplate

### PR DESCRIPTION
**Pull request by gmeligio**
## what

Update this module's test framework. Reduce boilerplate and make reusable functions.

Changelog:
1. Upgrade `go` to 1.21.
1. Update `test/Makefile` and `test/src/Makefile` from https://github.com/cloudposse/terraform-aws-eks-node-group/tree/e9f908c026d8ca5dc30190a050de68a510ff3983/test
1. Create framework_test.go and default_test.go, following how it's done in https://github.com/cloudposse/terraform-aws-eks-node-group/blob/e9f908c026d8ca5dc30190a050de68a510ff3983/test/src/framework_test.go
1. Remove `enabled=true` from fixtures and add new test `TestExamplesCompleteDisabled` for when `enabled=false`
1. Add `Test_ExistingDeployment` for faster test cycle, and modify Makefile accordingly
1. Update dependencies
1. Migrate test DB Engine from 3.6.0 to 5.0.0

## why

- Enable testing with OpenTofu
- Support automated maintenance

## references

- Closes #88 
- Closes #98
- https://github.com/cloudposse/terraform-aws-documentdb-cluster/pull/94
- https://github.com/cloudposse/terraform-aws-eks-node-group/tree/e9f908c026d8ca5dc30190a050de68a510ff3983/test/src
- https://github.com/cloudposse/terraform-aws-dynamic-subnets/tree/8528dadc5cbdcf657faa1d917c9f069c254f41a3/test/src

### CODE REVIEW

**Review by Benbentwo — DISMISSED** [review]
LGTM thanks everyone

**Review by Nuru — CHANGES_REQUESTED** [review]
@mcalhoun Has a bunch of improvements he told me he would like to see on these test (deferring more to Terratest, using more standard ways of skipping the "existing deployment" test, etc.), so let's give him a few days to make those changes.

**Review by Nuru — COMMENTED** [review]
@mcalhoun Will get to fixing these tests later. This is good enough for now. I added comments about how this is work-in-progress and should not be duplicated.

**Review by Nuru — APPROVED** [review]

**Pull request merged**
