### PR TITLE
feat(aws_docdb_cluster): add allow_major_version_upgrade argument

### PR DESCRIPTION
**Pull request by gmeligio**
## what

This PR adds the argument [allow_major_version_upgrade](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/docdb_cluster#allow_major_version_upgrade) that was released in https://github.com/hashicorp/terraform-provider-aws/releases/tag/v5.21.0

It includes with the changes in the test framework from https://github.com/cloudposse/terraform-aws-documentdb-cluster/pull/100 .

## why

When upgrading the `engine_version` to a new major version, `allow_major_version_upgrade` needs to be enabled for AWS to apply the upgrade.

## references

- https://github.com/hashicorp/terraform-provider-aws/releases/tag/v5.21.0
- https://awscli.amazonaws.com/v2/documentation/api/latest/reference/docdb/modify-db-cluster.html
- https://docs.aws.amazon.com/documentdb/latest/developerguide/docdb-mvu.html

### CODE REVIEW

**Comment by gmeligio** [comment]
Thank you for reviewing this @jamengual . The terratest job finished OK. Is there something that I should do before the review continues?

**Comment by Nuru** [comment]
@gmeligio Thank you for this PR. 

We do not expect contributors such as yourself to do more than you have done. Unfortunately, the test framework in this module is too old to allow us to allow a new version to be released with it. Merging this PR will have to wait until a Cloud Posse engineer can migrate this to the current framework. This may take a while.

**Review by Nuru — CHANGES_REQUESTED** [review]
@cloudposse/engineering @goruha This module's test framework needs major updates before we can allow it to be merged.

**Comment by gmeligio** [comment]
Thank you for the review. Let me know if the new testing methodology is in place in another CloudPosse module. I could help learning from that module and moving that forward here. I checked other CloudPosse modules that were recently updated before doing changes in the `test` folder but didn't notice any major difference with this one. It's great that you are thinking of updating it and taking the time to do so. Feel free to ping me @Nuru and @goruha if I can help.

I'm interested because I'm using the module and could contribute again soon. For example, I have the draft https://github.com/cloudposse/terraform-aws-documentdb-cluster/pull/95 and could have more to contribute.

**Comment by Nuru** [comment]
@gmeligio Thank you for the offer to update the tests. It's a big job and one that will take us a while to review, so please only do it if you are excited about the task. Here are my notes on what I would do, but they are shorthand and more needs to be done.

- `test/Makefile` and `test/src/Makefile` need to be updated. 
- `go.mod` is at `go` version 1.14, should be updated to 1.21 and dependencies updated.
- Test should be updated to use `CopyTerraformFolderToTemp` to allow for real parallel testing
- Test for `enabled=false` should be added
- `strconv.Itoa(rand.Intn(100000))` should be replaced with `strings.ToLower(random.UniqueId())` and `randId` replaced with `randID`

The general pattern of starting and cleaning up tests has changed, with the above noting some of the more detailed changes. 

- [Dynamic subnets](https://github.com/cloudposse/terraform-aws-dynamic-subnets/tree/main/test/src) is a good, though perhaps overly complicated, example. 
- You can look at [EKS workers](https://github.com/cloudposse/terraform-aws-eks-workers/blame/main/test/src/examples_complete_test.go), too, but it is not fully up to par.
- [Terraform example module](https://github.com/cloudposse/terraform-example-module/blob/main/test/src/examples_complete_test.go) gives you the basic idea of where we were a few years ago, and is cleaner and easier to understand.

If you are really ambitious, you can try reorganizing the code to accomplish the following objectives:
- Move more boilerplate/support to a separate file that can be common to all our tests. Things like set up and cleanup and random ID and error handling and Kubernetes and AWS clients could all go in there. The idea being that we should be able to update that file to be the same in every repo as our test framework evolves, leaving the test function focused on providing inputs, validating outputs, and making any other checks they need to make.
- Add an option to run the tests only as far as the `plan` phase and check the results. This would give us an option to test multiple versions of Terraform and OpenTofu for syntax and features without requiring us to go through all of the resource creation and cleanup each time.

I know the above is a lot to ask, so please do not feel any obligation to do it.

**Comment by gmeligio** [comment]
Hi, I created the intermediate https://github.com/cloudposse/terraform-aws-documentdb-cluster/pull/100 to update the test framework. I'll notify in slack too.

**Review by Nuru — APPROVED** [review]

**Pull request merged**
